name             'depot-cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures depot-cookbook'
long_description 'Installs/Configures depot-cookbook'
version          '0.2.7'

depends 'yum'
depends 'mysql'
depends 'apache2'
depends 'nginx'
depends 'passenger_apache2'
depends 'git'
depends 'chef-sugar'